AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template launches a single Amazon EC2 instance within an existing VPC. 
  It also creates a security group, allocates an Elastic IP, and installs a basic web server.
  The instance type and SSH key are passed in as parameters for reusability.

# The Parameters section allows you to customize values at runtime when creating the stack.
Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair in your account.
  
  VpcId:
    Description: The VPC ID where the EC2 instance will be launched.
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: Must be the ID of an existing VPC.

  SubnetId:
    Description: The Subnet ID where the EC2 instance will be launched.
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: Must be the ID of an existing subnet.

  InstanceType:
    Description: The EC2 instance type.
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
<<<<<<< HEAD
      - m5.large
=======
>>>>>>> 3294c3a352d1382668e8a2c3d0436d9da0b55952
    ConstraintDescription: Must be a valid EC2 instance type.
  
  SSHLocation:
    Description: >
      The IP address range that can be used to communicate with the EC2 instance over SSH.
      Defaults to allowing access from any IP address (0.0.0.0/0).
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
# The Resources section declares the AWS resources that will be created.
Resources:
  MyWebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP access for web server
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # Rule to allow SSH access (port 22) from the specified CIDR.
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        # Rule to allow HTTP access (port 80) from anywhere.
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-web-security-group"

  MyWebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      ImageId: ami-052064a798f08f0d3
 # This is a common Amazon Linux 2 AMI for us-east-1
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref MyWebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-web-instance"
      UserData:
        # The UserData script is executed when the instance is launched.
        # This one installs a web server (httpd) and starts it.
        # Fn::Base64 is used to encode the user data script.
        !Base64 |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from AWS CloudFormation</h1>" > /var/www/html/index.html
          echo "<h1>My Instance ID is: $(/usr/bin/ec2-metadata --instance-id)</h1>" >> /var/www/html/index.html

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref MyWebServerInstance
      
# The Outputs section exports important information about the created resources.
Outputs:
  InstancePublicIP:
    Description: Public IP address of the newly created EC2 instance.
    Value: !Ref MyEIP
    Export:
      Name: !Sub "${AWS::StackName}-PublicIP"
  
  InstancePublicURL:
    Description: URL to access the web server.
    Value: !Sub "http://${MyEIP}"
  
  SecurityGroupId:
    Description: The ID of the Security Group.
<<<<<<< HEAD
    Value: !Ref MyWebServerSecurityGroup
=======
    Value: !Ref MyWebServerSecurityGroup
>>>>>>> 3294c3a352d1382668e8a2c3d0436d9da0b55952
